### PR TITLE
bring in ui polish with latest code + add interactions between map and table

### PR DESCRIPTION
**Pull request by smcalilly**
## Overview
This PR has a ton of UI changes for issue #125. There are a lot of CSS changes and UI element tweaks. 

It also includes some React code changes for #120 and #96. The changes let a user select a row in the table which will open a popup for that row's geometry and allow the user to save that geometry. Similarly, a user can select a single geometry and save the geometry.

### Demo
Screen Shot 2022-02-16 at 3 56 30 PM
Screen Shot 2022-02-16 at 3 56 41 PM
Screen Shot 2022-02-16 at 3 57 06 PM
Screen Shot 2022-02-16 at 3 57 36 PM
Screen Shot 2022-02-16 at 3 57 53 PM

## Notes
At a high level, made these UI changes:
- widened the container that holds all the form elements
- branding: changed green for the header, added their logo, and used their icons
- changed all the links and buttons from dark green to light green
- most significant styling changes:
  - phase add / edit form
  - GIS tool

## Testing Instructions
- Review app: https://ccfp-asset-d-ui-polish-5fk6dqu.herokuapp.com
- Login with `ccfp-asset-dashboard test user` credentials in lastpass
- See the changes listed in the notes and make sure they look ok.

to test the map changes:
- click on a row in the table and confirm that the popup opens and you can save the selected asset
- click on an asset in the map and confirm that the popup opens and you can save the selected asset

### CODE REVIEW

**Comment by fgregg** [comment]
@smcalilly could you redeploy?

**Comment by smcalilly** [comment]
@fgregg here you go: https://ccfp-asset-d-ui-polish-tmvktzk.herokuapp.com

**Comment by fgregg** [comment]
looking slick. lets change visually change selected assets that have not been "saved" and let's also change the "save asset" button to "add asset to phase" button

**Comment by smcalilly** [comment]
@fgregg made the requested changes. in the process, i found an edge case that i fixed and [attempted to articulate in this code comment](https://github.com/fpdcc/ccfp-asset-dashboard/blob/8ebc8b16d0d856ed5f4af2469d5342ba6436aab7/asset_dashboard/static/js/components/maps/SelectAssetsMap.js#L154). i also changed the name of some variables to be more clear, because i found that parts of the code was hard to understand......despite being the writer of it......

here's a demo of how it looks/works:
select-asset

**Pull request merged**
