### PR TITLE
calculate political boundaries when an asset is saved + incorporate feature in project overview ui

### PR DESCRIPTION
**Pull request by smcalilly**
## Overview

For:
- #126 

#### How do we calculate this for production?
All of the projects on the production database already have districts associated with them. New relationships won't be created until they save some assets. Do we delete these existing relationships, or what?

I'm using a new text editor and it appears that I have a plugin installed that removed indentations on lines with no code. Sorry for the extra diff!

## Testing Instructions
- visit review app: https://ccfp-asset-d-feature-pr-awf7kf.herokuapp.com
- login with the `ccfp-asset-dashboard test user` credentials in last pass
- view a project and edit/add a phase. save some assets.
- revisit the project detail page and make sure the districts/zones were updated.

### CODE REVIEW

**Comment by fgregg** [comment]
> The house and senate district boundaries in their DB are dated 2017 and already out of date. Perhaps, regarding the geojson comment, you were thinking that we would download the latest political boundaries as geojson? If we want to do that, the import script will be easily adaptable.

yeah, it doesn't really make sense to have their DB to be the source of truth, and it's pretty easy to store these things statically

**Comment by fgregg** [comment]
i think it's fine to do it by hand, as long as you document in the README where you got them. for the zones, let's get the data from their database, but then save it as a geojson file so it's consistent with the others.

**Comment by smcalilly** [comment]
I got the geo data from public sources. I went ahead and wrote a makefile for the import script, it didn't take much time.

**Review by fgregg — APPROVED** [review]
this is super clean!

**Pull request merged**
